### PR TITLE
fix: check connected identity on `connect()`

### LINKED ISSUE #965: Bug injector service request connect identity page without checking current connected identity
The current implementation of connect function, the injector doesn't check the connected identity before requesting a connect identity page.
https://github.com/CryptKeeperZK/crypt-keeper-extension/blob/0246df68ed275d746377e35679c5b769aad0b244/packages/app/src/background/services/injector/Injector.ts#L66

### LINKED ISSUE #992: Bug the extension popup closes directly
This issue is still not fixed.

1. Reinstall the extension
2. Click connect identity
3. Complete the onboarding
4. Reject approving host
5. Open extension popup on the same page and lock it
6. Click connect identity on demo again
7. Login

Actual: it closes the extension popup
Expected: it should open approve screen.

_Originally posted by @0xmad in https://github.com/CryptKeeperZK/crypt-keeper-extension/pull/978#pullrequestreview-1665176510_

### PR DESCRIPTION
**Pull request by 0xisk**
## Explanation

This PR changes checks if there is a connected identity before sending a new request to connect identity page.

## Related Issues

* Blocked by #966 
* Fixes #965 
* Fixes #992 

## Screenshots

N/A

## Manual Testing Steps

N/A

## Pre-Merge Checklist

- [x] PR template is filled out
- [x] Pre-commit and pre-push hook checks are passed
- [x] E2E tests are passed locally
- [ ] **IF** this PR fixes a bug, a test that _would have_ caught the bug has been added
- [x] PR is linked to the appropriate GitHub issue
- [x] PR has been added to the appropriate release Milestone

> PR template source from [github.com/MetaMask](https://github.com/MetaMask)

### CODE REVIEW

File: packages/app/src/background/services/approval/index.ts [hunk 1]
```diff
@@ -45,6 +45,8 @@ export default class ApprovalService extends BaseService implements IBackupable
     if (encryped) {
       const decrypted = this.cryptoService.decrypt(encryped, { mode: ECryptMode.MNEMONIC });
       this.allowedHosts = new Map(JSON.parse(decrypted) as Iterable<[string, IHostPermission]>);
+      this.isUnlocked = true;
+      this.onUnlocked();
```
Comment (0xmad) [inline packages/app/src/background/services/approval/index.ts:49]: Let's remove it. Seems it's merged with old changes.

**Review by 0xmad — APPROVED** [review]
@0xisk thanks, just one comment to fix.

**Review by 0xmad — CHANGES_REQUESTED** [review]
This issue is still not fixed.

1. Reinstall the extension
2. Click connect identity
3. Complete the onboarding
4. Reject approving host
5. Open extension popup on the same page and lock it
6. Click connect identity on demo again
7. Login

Actual: it closes the extension popup
Expected: it should open approve screen.

File: pnpm-lock.yaml
Comment (0xmad) [inline pnpm-lock.yaml:1]: This file should be reverted.

Comment (0xisk) [reply pnpm-lock.yaml:1]: This commit should be reverted this new line https://github.com/CryptKeeperZK/crypt-keeper-extension/pull/978/commits/79058d2343b66cd91af43cfec7b120cb3b14367d But I sitll see that file in the changes.

**Comment by 0xisk** [comment]
@0xmad this change resolved this bug #992 

https://github.com/CryptKeeperZK/crypt-keeper-extension/blame/b11cf8db7d7db566dbbc9172bb6745e9085dacef/packages/app/src/ui/pages/Login/useLogin.ts#L46-L52

File: packages/demo/index.tsx [hunk 2]
```diff
@@ -98,6 +98,14 @@ const App = () => {
 
       <hr />
 
+      <div>
+        <h2>Connect identity</h2>
```
Comment (0xisk) [inline packages/demo/index.tsx:102]: Regarding adding the ability to change the connected identity, this change wont resolve it. Because that is another feature which is not supported yet its related to this: 
- #888 
- #945

Comment (0xisk) [reply packages/demo/index.tsx:102]: That is also related to the `Connected` and `Not Connected` word shown in the extension UI. Which in the current implementation it change to `Connected` if the user Approve but not necessary if the user choose an identity to connect with. Which means the user could approve from the approval screen and then could reject the next screen of choosing an identity, but at the same time you would see `Connected` which is confusing ofc for the user (technically and logically the connection didn't happen yet). 
That all should be resolved with another feature of having a separate connection service.

File: packages/app/src/ui/pages/Login/useLogin.ts [hunk 3]
```diff
@@ -43,9 +43,13 @@ export const useLogin = (): IUseLoginData => {
...
-    if (!isKeepOpen) {
-      dispatch(closePopup());
-    }
+    // TODO: I am not sure yet why is that is the cause for that bug:
+    // (https://github.com/CryptKeeperZK/crypt-keeper-extension/issues/992)
+    // When commented the bug was resolved.
+    // I think because at that scenario described in the bug issue, the pendingRequests would be already zero.
+    // if (!isKeepOpen) {
+    //   dispatch(closePopup());
+    // }
```
Comment (0xmad) [inline packages/app/src/ui/pages/Login/useLogin.ts:52]: It should be here. If you remove it, modal will not close at all if there is only one login step.

File: packages/demo/index.tsx (hunk 2 above)
Comment (0xmad) [reply packages/demo/index.tsx:102]: With this change I can change identities for demo without reinstalling the extension.

**Review by 0xmad — APPROVED** [review]
@0xisk please check updated version.
