### PR TITLE
fix: yup merkle source

### LINKED ISSUE #947: Requested refactoring changes on the `InjectorService`
Nested try-catch is not a good practice. Related to all the case in the file.

_Originally posted by @0xmad in https://github.com/CryptKeeperZK/crypt-keeper-extension/pull/875#discussion_r1339282550_

              I think comments here are redundant and for such validation we have yup package which is more flexible than conditions.

_Originally posted by @0xmad in https://github.com/CryptKeeperZK/crypt-keeper-extension/pull/875#discussion_r1337307912_
            

              This approach is not a good one. You can run these checks using the same logic checks for connect identity page.
The only one things you need to add are events and handlers.
ConfirmRequestModal is not a flexible component and if we need to change some submit logic or error handling the component will grow and will be unmaintainable until refactoring.

I have a task on my list to get rid of this component but before I need to move all current modals to pages.

_Originally posted by @0xmad in https://github.com/CryptKeeperZK/crypt-keeper-extension/pull/875#discussion_r1337324367_
            
              Let's use mui instead.

_Originally posted by @0xmad in https://github.com/CryptKeeperZK/crypt-keeper-extension/pull/875#discussion_r1337329847_
            
              Let's use mui instead.

_Originally posted by @0xmad in https://github.com/CryptKeeperZK/crypt-keeper-extension/pull/875#discussion_r1337549500_
            
              You should not render object as strings.

_Originally posted by @0xmad in https://github.com/CryptKeeperZK/crypt-keeper-extension/pull/875#discussion_r1337554410_
            
              This one needs to be removed from ConfirmRequestModal right after this PR. Right now we have two copy-paste components which do the same things.

_Originally posted by @0xmad in https://github.com/CryptKeeperZK/crypt-keeper-extension/pull/875#discussion_r1339294728_

### PR DESCRIPTION
**Pull request by 0xisk**
## Explanation

Using Yup for validating Merkle Proof Source.

## Related Issues

* Fixes #947 

## Screenshots

N/A

## Manual Testing Steps

N/A

## Pre-Merge Checklist

- [x] PR template is filled out
- [x] Pre-commit and pre-push hook checks are passed
- [ ] E2E tests are passed locally
- [ ] **IF** this PR fixes a bug, a test that _would have_ caught the bug has been added
- [x] PR is linked to the appropriate GitHub issue
- [x] PR has been added to the appropriate release Milestone

> PR template source from [github.com/MetaMask](https://github.com/MetaMask)

### CODE REVIEW

File: packages/app/src/background/services/validation/source.ts [hunk 1]
```diff
@@ -1,51 +1,45 @@
...
 export const validateMerkleProofSource = ({
   merkleProofSource,
 }: Partial<IMerkleProofInputs>): Partial<IMerkleProofInputs> => {
   if (!merkleProofSource) {
     throw new Error("CryptKeeper: please set a merkle proof source.");
   }
 
-  if (isMerkleProofStorageUrl(merkleProofSource)) {
-    const merkleStorageUrl: MerkleProofStorageUrl = merkleProofSource as MerkleProofStorageUrl;
+  if (typeof merkleProofSource === "string" && merkleProofStorageUrlSchema.isValidSync(merkleProofSource)) {
```
Comment (0xmad) [inline packages/app/src/background/services/validation/source.ts:28]: Why do you need typeof checks for ifs here?

File: packages/app/src/background/services/validation/source.ts [hunk 2]
```diff
@@ -1,51 +1,45 @@
-import { MerkleProofSource, MerkleProofStorageUrl } from "@cryptkeeperzk/types/dist/src/proof/zkProof";
-
-import type { IMerkleProof, IMerkleProofArtifacts, IMerkleProofInputs } from "@cryptkeeperzk/types";
+import { IMerkleProof, IMerkleProofArtifacts, IMerkleProofInputs, MerkleProofStorageUrl } from "@cryptkeeperzk/types";
+import * as yup from "yup";
```
Comment (0xmad) [inline packages/app/src/background/services/validation/source.ts:2]: Let's use named imports

File: packages/app/src/background/services/validation/source.ts [hunk 3]
```diff
@@ -1,51 +1,45 @@
-import { MerkleProofSource, MerkleProofStorageUrl } from "@cryptkeeperzk/types/dist/src/proof/zkProof";
-
-import type { IMerkleProof, IMerkleProofArtifacts, IMerkleProofInputs } from "@cryptkeeperzk/types";
+import { IMerkleProof, IMerkleProofArtifacts, IMerkleProofInputs, MerkleProofStorageUrl } from "@cryptkeeperzk/types";
```
Comment (0xmad) [inline packages/app/src/background/services/validation/source.ts:1]:
```suggestion
import type { IMerkleProof, IMerkleProofArtifacts, IMerkleProofInputs, MerkleProofStorageUrl } from "@cryptkeeperzk/types";
```

**Review by 0xmad — COMMENTED** [review]
@0xisk thanks, just some comments.

File: packages/app/src/background/services/validation/source.ts (hunk 1 above)
Comment (0xisk) [reply packages/app/src/background/services/validation/source.ts:28]: To switch between the types of the inputs, if its string that means most probably a URL. It might be a string object but it would fail.

File: packages/app/src/background/services/validation/source.ts (hunk 3 above)
Comment (0xisk) [reply packages/app/src/background/services/validation/source.ts:1]: I dont think we need to do this in case of imports from "@cryptkeeper/types" because we know that they are all types.

Comment (0xmad) [reply packages/app/src/background/services/validation/source.ts:1]: It's not about the indication that it's the type, it's about build optimization. In production bundle we don't need these types.

**Review by 0xmad — APPROVED** [review]
@0xisk thanks!
