### PR TITLE
fix: awaiting unlocked for Approval and ZkIdentity

### LINKED ISSUE #963: Bug in connect() unlocking checks
The current flow of the `checkLockStatus()` https://github.com/CryptKeeperZK/crypt-keeper-extension/blob/0246df68ed275d746377e35679c5b769aad0b244/packages/app/src/background/services/injector/InjectorHandler.ts#L98-105

Has a bug for not awaiting for the other services to be unlocked, it only awaits for the lock service which is not enough it should await approval and zkIdentity services. 

Steps to produce the bug: 
1. Open the demo 
2. Connect via connect identity button
3. Will show Login screen and then approve screen. 
4. Close the browser
5. Open the demo again
6. Connect via connect identity button
7. Then you should see the approval screen again because the allowedHosts were not updated yet because we dont await for the approval to be unlocked.

### LINKED ISSUE #964: Bug dapp calling `getConnectedIdentityMetadata()` while CK is locked
The current implementation of `getConnectedIdentityMetadata()`
https://github.com/CryptKeeperZK/crypt-keeper-extension/blob/0246df68ed275d746377e35679c5b769aad0b244/packages/app/src/background/services/injector/Injector.ts#L36-47

It directly goes to check the approval data of a url origin without making sure that the extension is unlocked and that the approval service would be unlocked too. So that the allowedHosts would be updated.

### LINKED ISSUE #965: Bug injector service request connect identity page without checking current connected identity
The current implementation of connect function, the injector doesn't check the connected identity before requesting a connect identity page.
https://github.com/CryptKeeperZK/crypt-keeper-extension/blob/0246df68ed275d746377e35679c5b769aad0b244/packages/app/src/background/services/injector/Injector.ts#L66

### PR DESCRIPTION
**Pull request by 0xisk**
## Explanation

Fixing three bugs in the injector service. Please see related issues section.

## Related Issues

* Fixes #963 

## Screenshots

N/A

## Manual Testing Steps

- Please try to test each bug from the bug description. 

## Pre-Merge Checklist

- [x] PR template is filled out
- [x] Pre-commit and pre-push hook checks are passed
- [x] E2E tests are passed locally
- [x] **IF** this PR fixes a bug, a test that _would have_ caught the bug has been added
- [x] PR is linked to the appropriate GitHub issue
- [x] PR has been added to the appropriate release Milestone

> PR template source from [github.com/MetaMask](https://github.com/MetaMask)

### CODE REVIEW

File: packages/app/src/background/services/zkIdentity/index.ts [hunk 1]
```diff
@@ -273,9 +282,33 @@ export default class ZkIdentityService implements IBackupable {
...
+    if (this.isUnlocked) {
+      return undefined;
+    }
+
+    return new Promise((resolve) => {
+      this.unlockCB = () => {
+        resolve(undefined);
+      };
+    });
+  };
```
Comment (0xmad) [inline packages/app/src/background/services/zkIdentity/index.ts:310]: This code is duplicated. It makes sense to move it to a separate service.

**Review by 0xmad — COMMENTED** [review]
@0xisk thanks, just one comment.

File: packages/app/src/background/services/zkIdentity/index.ts (hunk 1 above)
Comment (0xisk) [reply packages/app/src/background/services/zkIdentity/index.ts:310]: Yes, I found that having an abstract class with an abstract impl of lock would make sense than having a composition in this case. 

so that in the injector I can directly call `this.approveService.awaitUnlocked()` not `this.approveService.baseService.awaitUnlocked()`.

Comment (0xmad) [reply packages/app/src/background/services/zkIdentity/index.ts]: Yes, in this case abstract class works well.

**Comment by 0xmad** [comment]
@0xisk thanks, I found some issues.I tested this PR on Firefox.

Issue 1:
1. Connect to demo
2. Click "Reload" in extensions page
3. Click connect identity again

Actual: it opens connect identity modal
Expected: it shouldn't open connect identity modal
image

Issue 2:
1. Reinstall the extension
5. Click connect identity
6. Complete the onboarding
7. Reject approving host
8. Open extension popup on the same page and lock it
9. Click connect identity on demo again
10. Login

Actual: it closes the extension popup
Expected: it should open approve screen.

**Comment by 0xisk** [comment]
@0xmad thanks for the manual testings. 
- Issue # 1 is fixed in this PR #978
- Issue # 2 is solved here: https://github.com/CryptKeeperZK/crypt-keeper-extension/pull/966/commits/f33ead574bd50f99ccb8e38a03f17bec56a3d5fe

**Review by 0xmad — APPROVED** [review]
@0xisk thanks!
