### PR TITLE
fix: detect metamask wallet installed

### LINKED ISSUE #242: bug: detect if browser doesn't have a wallet
- Current behavior: 
In case of a browser without an Ethereum wallet (Metamask) the extension will cont. loading. 

- Expected behavior: 
The extension should inform user to install first an Ethereum wallet (Metamask). 

Image

### PR DESCRIPTION
**Pull request by 0xmad**
## Explanation

This PR fixes the state of extension when there is no metamask installed.

Details are below:
- [x] Replace `metamask-extension-provider` package with `@metamask/providers`
- [x] Check if wallet is injected
- [x] Fix loading state
- [x] Add metamask url and redirect to page

## More Information

Closes #242 

### Before

image

### After

image

## Manual Testing Steps

1. Disabled metamask extension
2. Login into crypt keeper
3. Click connect icon and go to install page
4. Check there is no step 3 if metamask is enabled

## Pre-Merge Checklist

- [x] PR template is filled out
- [ ] **IF** this PR fixes a bug, a test that _would have_ caught the bug has been added
- [x] PR is linked to the appropriate GitHub issue
- [x] PR has been added to the appropriate release Milestone

### + If there are functional changes:

- [ ] Manual testing complete & passed
- [ ] "Extension QA Board" label has been applied

> PR template source from [github.com/MetaMask](https://github.com/MetaMask)

### CODE REVIEW

File: src/ui/components/Header/index.tsx [hunk 1]
```diff
@@ -9,8 +11,15 @@ import { useWallet } from "@src/ui/hooks/wallet";
...
 
+const METAMASK_INSTALL_URL = "https://metamask.io/";
+
 export const Header = (): JSX.Element => {
-  const { address, isActivating, isActive, chain, onConnect, onDisconnect, onLock } = useWallet();
+  const { address, isActivating, isActive, isInjectedWallet, chain, onConnect, onDisconnect, onLock } = useWallet();
+  const isLoading = isActivating && isInjectedWallet;
+
+  const onGoToMetamaskPage = useCallback(() => {
+    browser.tabs.create({ url: METAMASK_INSTALL_URL });
```
Comment (iskdrews) [inline src/ui/components/Header/index.tsx:21]: I'm wondering why we didn't use `redirectToNewTab()` here? `src/util/browser.ts`

**Review by iskdrews — CHANGES_REQUESTED** [review]
Thanks @0xmad, I left one comment.

**Review by iskdrews — APPROVED** [review]
Thanks so much @0xmad!
