### PR TITLE
fix: removing `genExternalNullifier()`

### LINKED ISSUE #248: bug: `genExternalNullifier()` is not a function
Fixing this bug: https://github.com/CryptKeeperZK/crypt-keeper-extension/blob/49d20e3b254358e89f863edd2d6e6e50a6f19214/demo/index.tsx#L4

### PR DESCRIPTION
**Pull request by iskdrews**
## Explanation

Replacing `genExternalNullifier()` with `formatBytes32String()` from `@ethersproject/strings`

- Comments: 

1. Since `VerificationKeyT` type is not exported directly from `rlnjs` `index.ts` main script, I had to add this eslint ignore commit until it's resolved from RLN
https://github.com/CryptKeeperZK/crypt-keeper-extension/blob/690f274f0c6a462253bdf47e3879d4ea439ef12c/src/background/services/protocols/utils.ts#L4-L5

2. Since I removed `declare module "rlnjs"` from `custom.d.ts`, I got this test error from `protocols.tests.ts` at this line (https://github.com/CryptKeeperZK/crypt-keeper-extension/blob/690f274f0c6a462253bdf47e3879d4ea439ef12c/src/background/services/protocols/__tests__/protocols.test.ts#L62) :
```
Conversion of type 'typeof RLN' to type 'Mock<any, any, any>' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
``` 
I just resolved it by casting first to unknown, but I think there is a better way of resolving this. 

## More Information

- Fixes #248 

### Before

N/A

### After

N/A

## Pre-Merge Checklist

- [x] PR template is filled out
- [x] **IF** this PR fixes a bug, a test that _would have_ caught the bug has been added
- [x] PR is linked to the appropriate GitHub issue
- [x] PR has been added to the appropriate release Milestone

### + If there are functional changes:

- [ ] Manual testing complete & passed
- [ ] "Extension QA Board" label has been applied

> PR template source from [github.com/MetaMask](https://github.com/MetaMask)

### CODE REVIEW

File: demo/index.tsx [hunk 1]
```diff
@@ -1,9 +1,10 @@
 /* eslint-disable no-console */
 import React, { useState, useEffect, useCallback } from "react";
 import { createRoot } from "react-dom/client";
-import { RLN, genExternalNullifier } from "rlnjs";
+import { RLN } from "rlnjs";
 import { bigintToHex } from "bigint-conversion";
 import { Identity } from "@semaphore-protocol/identity";
+import { formatBytes32String } from "@ethersproject/strings";
```
Comment (0xmad) [inline demo/index.tsx:7]: You don't need this dependency and you can use `encodeBytes32String` from `ethers`.

File: src/background/services/protocols/utils.ts [hunk 2]
```diff
@@ -59,6 +61,13 @@ export async function getMerkleProof({
       });
 }
 
+export async function getRlnVerficationKeyJson(rlnVerificationKeyPath: string): Promise<VerificationKeyT> {
+  const verificationKeyResponse = await fetch(rlnVerificationKeyPath);
+  const verificationKeyJson = (await verificationKeyResponse.json()) as VerificationKeyT;
+
+  return verificationKeyJson;
+}
```
Comment (0xmad) [inline src/background/services/protocols/utils.ts:69]:
```suggestion
  return fetch(rlnVerificationKeyPath).then((res) => res.json());
}
```

File: src/background/services/protocols/utils.ts [hunk 3]
```diff
@@ -1,6 +1,8 @@
 import { Group, BigNumberish } from "@semaphore-protocol/group";
 import { MerkleProof } from "@zk-kit/incremental-merkle-tree";
 import { bigintToHex, hexToBigint } from "bigint-conversion";
+// eslint-disable-next-line import/no-unresolved
+import { VerificationKeyT } from "rlnjs/dist/types/types";
```
Comment (0xmad) [inline src/background/services/protocols/utils.ts:5]: I'd move it to our types until it's exported properly.

**Review by 0xmad — CHANGES_REQUESTED** [review]
@iskdrews thanks, just few commets

File: package-lock.json
Comment (0xmad) [inline package-lock.json:1]: This file should not contain any changes because you don't have any updates in package.json.
I usually run `npm remove dep-name` and it will clean package.json and lock files.

**Review by 0xmad — APPROVED** [review]
@iskdrews looks good to me! Thanks.
